# Generated by Django 3.2.12 on 2022-05-05 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tomeet',
            name='phone_number',
        ),
    ]
