# Generated by Django 3.2.12 on 2022-05-05 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0002_remove_tomeet_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToMeets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('persone', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=12)),
                ('date_of_meeting', models.DateField(auto_now_add=True)),
                ('comment', models.CharField(max_length=12)),
                ('is_closed', models.BooleanField(default=False)),
                ('is_favorite', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='ToMeet',
        ),
    ]
