# Generated by Django 3.2.12 on 2022-05-05 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0003_auto_20220505_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tomeets',
            name='comment',
            field=models.CharField(max_length=100),
        ),
    ]
