# Generated by Django 3.2.12 on 2022-05-07 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0006_alter_tomeet_date_of_meeting'),
    ]

    operations = [
        migrations.CreateModel(
            name='Habits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('done_for_today', models.IntegerField(default=0)),
                ('important', models.BooleanField(default=False)),
                ('comment', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='tomeet',
            name='phone_number',
            field=models.IntegerField(default=0),
        ),
    ]
